<a href="https://colab.research.google.com/github/madhu-1013/DS_internship/blob/main/DS_intern_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **BASICS**



In [ ]:
print("hello world!")

hello world!


In [ ]:
x=5
m=6
y="9"
z="2"
print(type(x))
print(type(y))
print(x+m)
print(y+z)

<class 'int'>
<class 'str'>
11
92


In [ ]:
#typecasting
a=int(z)
print(a+m)
""" is used to comment multiline
like this
"""

8


' is used to comment multiline\nlike this\n'

In [ ]:
#list
l1=['hi',1,7,'list',6.7,9.5,[3,59,'hello']]
l2=l1[6][2] #indexerror: list index out of range if l2=[6][5]
print(l2)
length=len(l1)
print(length)


hello
7


In [ ]:
#python program to illustraate a list
# creates an empty list
nums=[]
#appending data in list
nums.append(21)
nums.append(40.5)
nums.append("string")
print(nums)

[21, 40.5, 'string']


In [ ]:
#tuple
t1=(1,3,7)
print(t1)


(1, 3, 7)


In [ ]:
#dictionary
d1={'Name': 'XYZ','age': 21,'proff':'student'}
print(d1)
print(d1.keys())
print(d1.items())
print(d1.values())
print(d1['Name'])


{'Name': 'XYZ', 'age': 21, 'proff': 'student'}
dict_keys(['Name', 'age', 'proff'])
dict_items([('Name', 'XYZ'), ('age', 21), ('proff', 'student')])
dict_values(['XYZ', 21, 'student'])
XYZ


In [ ]:
#accepting integer from user
#return type of input() function is string
num=int(input("enter a no\n"))

if (num>12):
  print("num1 is good")
elif(num>35):
  print("num1 is not good")
else:
  print("num1 is great")

enter a no
7
num1 is great


# **NUMPY**

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,2,5]])
print("array is of type:",type(arr))
print("no of dimension:",arr.ndim)
print("shape of array:",arr.shape)
print("size :",arr.size)
print("data type:",arr.dtype)

array is of type: <class 'numpy.ndarray'>
no of dimension: 2
shape of array: (2, 3)
size : 6
data type: int64


In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,2,5]])
print("array with rank2:",arr)

array with rank2: [[1 2 3]
 [4 2 5]]


In [ ]:
import numpy as np
a=np.arange(10,1,-2)
print("a sequential array with a negative step:\n",a)
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)

a sequential array with a negative step:
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
import numpy as np

# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [ ]:
import numpy as np

# creating array
arr = np.array([2, 4, 6, 8, 10])

# creating copy of array
c = arr.copy()

# both arr and c have different id
print("id of arr", id(arr))
print("id of c", id(c))

# changing original array, this will not effect copy
arr[0] = 12
# printing array and copy
print("original array- ", arr)
print("copy- ", c)

id of arr 139555768232496
id of c 139554804417904
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [ ]:
def sum(array):
	sum = 0
	# Parse through our array
	for i in array:
		sum += i

	# Return our sum
	return sum
testArray = [1, 3, 34, 92, 29, 48, 20.3]
print('The sum of your numbers is ' + str(sum(testArray)))

The sum of your numbers is 227.3


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
# Create an array with 5 dimensions using ndmin
#using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


# **PANDAS**

In [ ]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}
myvar = pandas.DataFrame(mydataset)
print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
import pandas as pd
print(pd.__version__)

2.0.3


In [ ]:
import pandas as pd

a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)
print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)
#Pandas use the loc attribute to return one or more specified row(s)
#refer to the row index:
print(df.loc[0])
#Returns a pandas series
#use a list of indexes:
print(df.loc[[0, 1]])
#When using [], the result is a Pandas DataFrame.

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [ ]:
import pandas as pd

df = pd.read_csv('Data.csv')

print(df.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
import pandas as pd

df = pd.read_csv('Data.csv')

print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
import pandas as pd

print(pd.options.display.max_rows)

60


In [ ]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('Data.csv')

print(df)

print(pd.options.display.max_rows)

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
..      ...   ...      ...       ...
6     Spain   NaN  52000.0        No
7    France  48.0  79000.0       Yes
8   Germany  50.0  83000.0        No
9    France  37.0  67000.0       Yes

[10 rows x 4 columns]
9


In [ ]:
#Load a Python Dictionary into a DataFrame   JSON= Python Dictionary
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [ ]:
# importing the module
import pandas as pd

# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana", "avocado"],
					"market_price" : [21, 14, 35]})
display("The first DataFrame")
display(df1)

# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["banana", "apple", "avocado"],
					"wholesaler_price" : [65, 68, 75]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")
# how : {‘left’, ‘right’, ‘outer’, ‘inner’}, default ‘inner’


'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35

'The second DataFrame'

fruit  wholesaler_price
0   banana                65
1    apple                68
2  avocado                75

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21                68
1   banana            14                65
2  avocado            35                75

from matplotlib import pyplot as plt
df1['market_price'].plot(kind='hist', bins=20, title='market_price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df1.groupby('fruit').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1['market_price'].plot(kind='line', figsize=(8, 4), title='market_price')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df1['fruit'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df1, x='market_price', y='fruit', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
_df_0['market_price'].plot(kind='hist', bins=20, title='market_price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['wholesaler_price'].plot(kind='hist', bins=20, title='wholesaler_price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('fruit').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='market_price', y='wholesaler_price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4['market_price'].plot(kind='line', figsize=(8, 4), title='market_price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_5['wholesaler_price'].plot(kind='line', figsize=(8, 4), title='wholesaler_price')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_6['fruit'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_6, x='market_price', y='fruit', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_7['fruit'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_7, x='wholesaler_price', y='fruit', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
#Merging two data frames with different number of elements
# importing the module
import pandas as pd

# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana",
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
display("The first DataFrame")
display(df1)

# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
# here both common DataFrame elements are in df1 and df2,
# so it extracts apple, banana, grapes from df1 and df2.
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

pd.merge(df1, df2, on = "fruit", how = "outer")

'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35
3    grape            38

'The second DataFrame'

fruit  wholesaler_price
0   apple                65
1  banana                68
2   grape                71

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21              65.0
1   banana            14              68.0
2  avocado            35               NaN
3    grape            38              71.0

from matplotlib import pyplot as plt
df1['market_price'].plot(kind='hist', bins=20, title='market_price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df1.groupby('fruit').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df1['market_price'].plot(kind='line', figsize=(8, 4), title='market_price')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df1['fruit'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df1, x='market_price', y='fruit', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
df2['wholesaler_price'].plot(kind='hist', bins=20, title='wholesaler_price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df2.groupby('fruit').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['wholesaler_price']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'wholesaler_price'}, axis=1)
              .sort_values('wholesaler_price', ascending=True))
  xs = counted['wholesaler_price']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df2.sort_values('wholesaler_price', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('fruit')):
  _plot_series(series, series_name, i)
  fig.legend(title='fruit', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('wholesaler_price')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
df2['wholesaler_price'].plot(kind='line', figsize=(8, 4), title='wholesaler_price')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df2['fruit'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df2, x='wholesaler_price', y='fruit', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
import pandas as pd

# Creating the dataframe
df = pd.read_csv("nba.csv")

# Print the dataframe
print(df.head())

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0  


In [ ]:
gk = df.groupby('Team')

# Let's print the first entries in all the groups formed.
gk.first()

Name  Number Position   Age Height  Weight  \
Team                                                                          
Atlanta Hawks           Kent Bazemore    24.0       SF  26.0    6-5   201.0   
Boston Celtics          Avery Bradley     0.0       PG  25.0    6-2   180.0   
Brooklyn Nets        Bojan Bogdanovic    44.0       SG  27.0    6-8   216.0   
Charlotte Hornets       Nicolas Batum     5.0       SG  27.0    6-8   200.0   
...                               ...     ...      ...   ...    ...     ...   
San Antonio Spurs   LaMarcus Aldridge    12.0       PF  30.0   6-11   240.0   
Toronto Raptors       Bismack Biyombo     8.0        C  23.0    6-9   245.0   
Utah Jazz               Trevor Booker    33.0       PF  28.0    6-8   228.0   
Washington Wizards      Alan Anderson     6.0       SG  33.0    6-6   220.0   

                                  College      Salary  
Team                                                   
Atlanta Hawks                Old Dominion   2000000.0  
Boston Celtics                      Texas   7730337.0  
Brooklyn Nets              Oklahoma State   3425510.0  
Charlotte Hornets   Virginia Commonwealth  13125306.0  
...                                   ...         ...  
San Antonio Spurs                   Texas  19689000.0  
Toronto Raptors                  Missouri   2814000.0  
Utah Jazz                         Clemson   4775000.0  
Washington Wizards         Michigan State   4000000.0  

[30 rows x 8 columns]

In [ ]:
# Finding the values contained in the "Boston Celtics" group
gk.get_group('Boston Celtics')

Name            Team  Number Position   Age Height  Weight  \
0   Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1     Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2    John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3     R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
..            ...             ...     ...      ...   ...    ...     ...   
11  Isaiah Thomas  Boston Celtics     4.0       PG  27.0    5-9   185.0   
12    Evan Turner  Boston Celtics    11.0       SG  27.0    6-7   220.0   
13    James Young  Boston Celtics    13.0       SG  20.0    6-6   215.0   
14   Tyler Zeller  Boston Celtics    44.0        C  26.0    7-0   253.0   

              College     Salary  
0               Texas  7730337.0  
1           Marquette  6796117.0  
2   Boston University        NaN  
3       Georgia State  1148640.0  
..                ...        ...  
11         Washington  6912869.0  
12         Ohio State  3425510.0  
13           Kentucky  1749840.0  
14     North Carolina  2616975.0  

[15 rows x 9 columns]

In [ ]:
#Indentation
j = 1

while(j<= 5):
	print(j)
	j = j + 1

1
2
3
4
5
